### ISSUE TITLE
Set up Kanban board

### ISSUE THREAD

**Issue by darikmohammed** [darikmohammed/Space_Travelers_Hub#25]
## Github project link
https://github.com/darikmohammed/Space_Travelers_Hub/projects/1

##Number of Team members
> There are 2 members in this group 
@dqarias and @darikmohammed

**Comment by keroloussamy** [comment]
Hi Team

Your project is complete!  There is nothing else to say other than...
Congratulations! 🎉 

Cheers and Happy coding!👏👏👏
